### ISSUE TITLE
css-variables

### ISSUE THREAD

**Issue by kesla** [reimertz/brand-colors#11]
Would be great if this module could extract css-variables, so it can be used together with https://github.com/postcss/postcss-custom-properties (I know there's already https://github.com/postcss/postcss-brand-colors and that's what we're using but we'd like to focus on custom properties going forward).

I might have some bandwidth to contribute this. Interested?

**Comment by reimertz** [comment]
Of course! Let's do it!

**Comment by kesla** [comment]
Perfect, expect a PR in a day or so!



—

**Comment by reimertz** [comment]
@kesla How are you doin? Im closing this since it's really an issue on my side you know. :)

**Comment by kesla** [comment]
Oh, thanks yeah let's close this! I'll see when I get bandwidth for this.
