### ISSUE TITLE
Duplicate colors

### ISSUE THREAD

**Issue by reimertz** [reimertz/brand-colors#21]
There's a couple duplicates, bing and bing-2, wordpress-com-7 and 8, and on the far left of the 3rd row from the bottom is two that are identical and both named wordpress-com.

**Comment by NickIrwin980** [comment]
googleplus and google-plus are also duplicated.

**Comment by reimertz** [comment]
@NickIrwin980  :+1:

**Comment by bobbybouwmann** [comment]
dunked-2 is also a duplicate!
