### ISSUE TITLE
Investigate the addition of logos

### ISSUE THREAD

**Issue by reimertz** [reimertz/brand-colors#29]
inorder for this to work, we would need to collect logos for the majority of colors, I would argue that they shouldn't be visible by default, but rather being activated by using a toggle. 

We currently store information about colors in /data/brandColors.js so I would say that 
logos should be placed in /data/logos/<brandname>.svg. 

We could then write a script that would, based on if there is an logo, generate base64'd versions and
inject them on the static page.

Also, it might be problematic since all logos aren't squared, meaning that it might reduce the simplicity of 
our current design.

**Comment by kjbrum** [comment]
I did something similar to this a while back, not with as many logos.

Just for some inspiration/help:
http://codepen.io/kjbrum/full/WbjbPr/

**Comment by reimertz** [comment]
@kjbrum that is really cool! I don't know thought. Do you think this fits the current design? I really like the simplicity and is afraid the introduction of logos might add to much noise. 

But please feel free to  fork and investigate if one can introduce logos while keeping it simple.

**Comment by kjbrum** [comment]
Might be cool if you were to make the grid of colors fill the screen and then when someone clicks on one, it fills the viewport and displays the additional information.

Could also have the company name pop up on hover?

Just some things to think about.

**Comment by reimertz** [comment]
I am closing this for due no to real progress for a long time. more than happy to open this again if someone would like to work on this again. :)
