### ISSUE TITLE
Add Telegram

### ISSUE THREAD

**Issue by ai** [reimertz/brand-colors#34]
[Telegram](https://en.wikipedia.org/wiki/Telegram_(software)) is one of the popular messager. “In September 2015, an announcement stated the app had 60 million active users and delivered 12 billion daily messages”

Also we need Telegram color to use it in our site with our awesome tool.

Official site uses `#179cde` color. I think we can take it.

/cc @reimertz

**Comment by reimertz** [comment]
Cool, thanks. Can you do a pull-request with this color? 😍

**Comment by ai** [comment]
Hm. Seems like you already have `telegram` color. Maybe I use old `brand-colors` in PostCSS plugin?

**Comment by reimertz** [comment]
Yeah, I bumped the version to + 1.0.0. there might be braking changes, but don't think so. Let me know if get any problems updating your dependencies.

**Comment by ai** [comment]
Done, plugin 0.4 release uses latest brand-colors.

**Comment by reimertz** [comment]
Dope. Glad to hear there was no issues. :guitar:

**Comment by ai** [comment]
I also start to watch this repo to do not miss next major release.
