### ISSUE TITLE
how can I copy the css variable

### ISSUE THREAD

**Issue by gitdust** [reimertz/brand-colors#44]
Wonderful thing!
My issue is in your homepage , I can just only copy the color RGB value , is there anyway that alow me to copy the css variable name ?

**Comment by reimertz** [comment]
interesting question. I guess I could add alt-click to get the css variable instead if that would be sufficient?

**Comment by gitdust** [comment]
That will be great!
Appreciate that!

**Comment by reimertz** [comment]
Dammit, clipboard.js doesn't pass down the event in their handler. I need to think about more about how to handle this.

**Comment by gitdust** [comment]
Maybe you can simply put two buttons，let users choose the type they want to copy?
