### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by ai** [reimertz/brand-colors#55]
Changelog is very important for every open source users. I found major 2.0 release, but without Changelog I can’t be sure, that it is safe to update my production.

Here are other reasons why Changelog is important: http://keepachangelog.com/ru/1.0.0/

As I open source author I know how lazy we are sometimes. But I have Changelog in every my project.

**Comment by reimertz** [comment]
@ai thanks for pointing it out. Will add straight away!

**Comment by reimertz** [comment]
fixed with https://github.com/reimertz/brand-colors/commit/3626723f9a5bee90ed36731777e4ebdf536c0e5f.
