### ISSUE TITLE
Check and update readme.md with the right filepaths

### ISSUE THREAD

**Issue by VladShcherbin** [reimertz/brand-colors#6]
Hello, please check the readme.md and correct the filepaths in the `Usage` section.

I needed only the scss version, so didn't check the other ones. **dist** dir should be added everywhere at least.

e.g.:
```
@import 'bower_components/brand-colors/latest/scss/brand-colors.scss'
```
should be
```
@import 'bower_components/brand-colors/dist/latest/scss/brand-colors.latest.scss'
```

Thanks for the package ;)

**Comment by reimertz** [comment]
Oh shit, thanks for catching this and sorry for the late reply, will fix asap!
