### ISSUE TITLE
well, I lost brand-colors.com

### ISSUE THREAD

**Issue by reimertz** [reimertz/brand-colors#64]
Omg, I hate this sh*t. I get it, domains are like property. Just wish there could be nice people out there.

I need to find out who is hosting current spam version of brand-colors.com and take it down.

**Comment by Potherca** [comment]
Am I missing something or is https://brand-colors.com/ back the way it should be?

**Comment by gistchat** [comment]
No, the douche copy-pasted my site, changed the links to go to some sketchy
pages. I tried reaching out to the host of the page / domain handlers but
no one will help me.

Seems like pretty sketchy behavior and a good reason to revoke the
ownership of the domain but I’ll have to pay $2000 to just have the
investigation started. :(

**Comment by Potherca** [comment]
That sucks :disappointed: I've seen this happen at other projects. Unless you are still in the 3 month grace period there isn't much to be done. Eventually the douche will loose interest and/or the domain will become available again, but that can take years. 

The best thing for it might be to just grab a different domain and move on...

**Comment by reimertz** [comment]
If someone reads this. I did move on. I bough a very expensive domain. Gave up the idea of owning individual domains and just start using sub-domains instead. I'll save money and I really don't care about the value of each domain. 

[brand-colors.re.im](brand-colors.re.im) [brand-colors.re.im](brand-colors.re.im) [brand-colors.re.im](brand-colors.re.im) [brand-colors.re.im](brand-colors.re.im) [brand-colors.re.im](brand-colors.re.im) [brand-colors.re.im](brand-colors.re.im)

**Comment by erikgaal** [comment]
@reimertz Your link is pointing to `https://github.com/reimertz/brand-colors/issues/brand-colors.re.im`, you should prepend `https://`, or use Markdown to make it link to the right place.

**Comment by gregjw** [comment]
what the heck

**Comment by reimertz** [comment]
> @reimertz Your link is pointing to `https://github.com/reimertz/brand-colors/issues/brand-colors.re.im`, you should prepend `https://`, or use Markdown to make it link to the right place.

Fixed. Thank you!

**Comment by codycraven** [comment]
Should be able to file a DMCA takedown for free with minimal effort since they copied your work. Can use Way Back Machine to prove copyright infringement.

Won't stop them from setting up a new version, but it would create a pile of hassle and work for them.

**Comment by reimertz** [comment]
> Should be able to file a DMCA takedown for free with minimal effort since they copied your work. Can use Way Back Machine to prove copyright infringement.
> 
> Won't stop them from setting up a new version, but it would create a pile of hassle and work for them.
> 
> Edit: And I just realized this happened back in June 🤦‍♂️, thanks HackerNews. DMCA is still valid though if they're still using your design and/or copy.

Thanks for replying. I tried to invoke this but I hit a brick wall with cloudflare who host the site and I gave up.

Tbh, the embarrassment of losing the domain just got me to table flip the whole
domain thing. :)

**Comment by Potherca** [comment]
> Expires on 2020-09-29

Mark it in your calender and check each year untill they give up 😀
