### ISSUE TITLE
Invalid colour code

### ISSUE THREAD

**Issue by KhairulA** [reimertz/brand-colors#65]
Using NPM's [brand-colors](https://www.npmjs.com/package/brand-colors), v2.0.1.

Colour code for `.bc-pac-12-7` is `#d3c4a`. Hex should be 6 characters.

- `brand-colors/dist/latest/scss/brand-colors.latest.scss:1113`
- `brand-colors/dist/latest/scss/brand-colors.latest.scss:2968`

**Comment by reimertz** [comment]
fixed.
